[2024-12-26T06:16:29.418+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T06:16:30.421+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-26T00:00:00+00:00 [queued]>
[2024-12-26T06:16:31.418+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-26T00:00:00+00:00 [queued]>
[2024-12-26T06:16:31.418+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-26T06:16:32.007+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_produce_data> on 2024-12-26 00:00:00+00:00
[2024-12-26T06:16:33.213+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T06:16:33.613+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2024-12-26T06:16:33.312+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'api_to_kafka_pipeline', 'fetch_and_produce_data', 'scheduled__2024-12-26T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/api_to_kafka_dag.py', '--cfg-path', '/tmp/tmp_b8viugo']
[2024-12-26T06:16:33.711+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask fetch_and_produce_data
[2024-12-26T06:16:36.415+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data scheduled__2024-12-26T00:00:00+00:00 [running]> on host a7d7ef0c0878
[2024-12-26T06:16:39.606+0000] {job.py:229} INFO - Heartbeat recovered after 11.48 seconds
[2024-12-26T06:16:40.011+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_to_kafka_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_produce_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-26T00:00:00+00:00'
[2024-12-26T06:16:40.012+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T06:16:40.435+0000] {logging_mixin.py:190} INFO - âœ… Data fetched successfully for IBM at 5min interval.
[2024-12-26T06:16:40.439+0000] {logging_mixin.py:190} INFO - ðŸš€ Sending data to Kafka...
[2024-12-26T12:29:28.170+0000] {job.py:229} INFO - Heartbeat recovered after 20483.71 seconds
[2024-12-26T13:54:42.264+0000] {job.py:229} INFO - Heartbeat recovered after 5114.19 seconds
[2024-12-26T16:09:54.302+0000] {job.py:229} INFO - Heartbeat recovered after 665.20 seconds
[2024-12-26T16:10:40.080+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-26T16:10:40.086+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-26T16:10:40.097+0000] {process_utils.py:132} INFO - Sending 15 to group 280. PIDs of all processes in the group: [280]
[2024-12-26T16:10:40.105+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 280
[2024-12-26T16:11:40.129+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=280, name='airflow task ru', status='sleeping', started='06:16:31') did not respond to SIGTERM. Trying SIGKILL
[2024-12-26T16:11:40.190+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 280
[2024-12-26T16:11:40.246+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=280, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='06:16:31') (280) terminated with exit code -9
[2024-12-26T16:11:40.248+0000] {standard_task_runner.py:190} ERROR - ('Job 79 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
