[2024-12-24T22:11:48.907+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:11:48.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:11:48.914+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:11:48.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:11:48.944+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:11:48.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:11:48.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:11:48.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.078 seconds
[2024-12-24T22:12:19.393+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:12:19.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:12:19.400+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:12:19.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:12:19.416+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:12:19.412+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:12:19.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:12:19.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.061 seconds
[2024-12-24T22:12:49.828+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:12:49.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:12:49.831+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:12:49.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:12:49.856+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:12:49.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:12:49.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:12:49.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.059 seconds
[2024-12-24T22:13:20.276+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:13:20.277+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:13:20.279+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:13:20.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:13:20.301+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:13:20.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:13:20.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:13:20.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.058 seconds
[2024-12-24T22:15:11.158+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:15:11.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:15:11.164+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:15:11.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:15:11.192+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:15:11.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:15:11.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:15:11.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.085 seconds
[2024-12-24T22:15:41.627+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:15:41.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:15:41.640+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:15:41.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:15:41.665+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:15:41.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:15:41.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:15:41.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.120 seconds
[2024-12-24T22:16:12.348+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:16:12.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:16:12.352+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:16:12.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:16:12.385+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:16:12.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:16:12.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:16:12.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.094 seconds
[2024-12-24T22:16:42.842+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:16:42.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:16:42.846+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:16:42.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:16:42.866+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:16:42.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:16:42.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:16:42.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.120 seconds
[2024-12-24T22:17:13.282+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:17:13.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:17:13.285+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:17:13.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:17:13.297+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:17:13.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:17:13.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:17:13.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.090 seconds
[2024-12-24T22:17:43.703+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:17:43.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:17:43.716+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:17:43.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:17:43.771+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:17:43.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:17:43.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:17:43.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.110 seconds
[2024-12-24T22:18:14.139+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:18:14.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:18:14.144+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:18:14.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:18:14.171+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:18:14.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:18:14.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:18:14.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.075 seconds
[2024-12-24T22:18:44.593+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:18:44.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:18:44.598+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:18:44.598+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:18:44.621+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:18:44.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:18:44.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:18:44.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.217 seconds
[2024-12-24T22:19:15.190+0000] {processor.py:186} INFO - Started process (PID=356) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:19:15.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:19:15.194+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:19:15.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:19:15.207+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:19:15.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:19:15.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:19:15.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.044 seconds
[2024-12-24T22:19:45.616+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:19:45.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:19:45.620+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:19:45.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:19:45.636+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:19:45.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:19:45.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:19:45.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.075 seconds
[2024-12-24T22:20:16.073+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:20:16.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:20:16.076+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:20:16.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:20:16.091+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:20:16.088+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:20:16.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:20:16.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.045 seconds
[2024-12-24T22:20:46.503+0000] {processor.py:186} INFO - Started process (PID=404) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:20:46.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:20:46.507+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:20:46.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:20:46.523+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:20:46.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:20:46.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:20:46.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.050 seconds
[2024-12-24T22:21:16.899+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:21:16.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:21:16.902+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:21:16.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:21:16.920+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:21:16.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:21:16.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:21:16.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.053 seconds
[2024-12-24T22:21:47.352+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:21:47.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:21:47.355+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:21:47.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:21:47.372+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:21:47.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:21:47.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:21:47.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.054 seconds
[2024-12-24T22:22:17.827+0000] {processor.py:186} INFO - Started process (PID=458) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:22:17.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:22:17.833+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:22:17.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:22:17.861+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:22:17.855+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:22:17.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:22:17.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.064 seconds
[2024-12-24T22:22:48.277+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:22:48.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:22:48.281+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:22:48.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:22:48.305+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:22:48.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:22:48.306+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:22:48.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.058 seconds
[2024-12-24T22:23:18.746+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:23:18.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:23:18.749+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:23:18.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:23:18.774+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:23:18.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:23:18.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:23:18.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.062 seconds
[2024-12-24T22:23:49.189+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:23:49.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:23:49.192+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:23:49.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:23:49.214+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:23:49.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:23:49.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:23:49.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.054 seconds
[2024-12-24T22:24:19.650+0000] {processor.py:186} INFO - Started process (PID=521) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:24:19.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:24:19.653+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:24:19.653+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:24:19.671+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:24:19.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:24:19.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:24:19.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.050 seconds
[2024-12-24T22:24:50.107+0000] {processor.py:186} INFO - Started process (PID=537) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:24:50.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:24:50.111+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:24:50.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:24:50.129+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:24:50.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:24:50.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:24:50.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.052 seconds
[2024-12-24T22:25:20.643+0000] {processor.py:186} INFO - Started process (PID=553) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:25:20.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:25:20.648+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:25:20.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:25:20.667+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:25:20.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:25:20.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:25:20.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.052 seconds
[2024-12-24T22:25:51.123+0000] {processor.py:186} INFO - Started process (PID=569) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:25:51.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:25:51.132+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:25:51.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:25:51.153+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:25:51.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:25:51.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:25:51.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.063 seconds
[2024-12-24T22:26:21.649+0000] {processor.py:186} INFO - Started process (PID=585) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:26:21.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:26:21.653+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:26:21.653+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:26:21.676+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:26:21.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:26:21.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:26:21.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.057 seconds
[2024-12-24T22:26:52.110+0000] {processor.py:186} INFO - Started process (PID=601) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:26:52.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:26:52.113+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:26:52.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:26:52.137+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:26:52.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:26:52.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:26:52.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.057 seconds
[2024-12-24T22:27:22.578+0000] {processor.py:186} INFO - Started process (PID=617) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:27:22.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:27:22.582+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:27:22.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:27:22.602+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:27:22.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:27:22.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:27:22.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.055 seconds
[2024-12-24T22:27:53.088+0000] {processor.py:186} INFO - Started process (PID=633) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:27:53.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:27:53.091+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:27:53.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:27:53.104+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:27:53.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:27:53.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:27:53.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.041 seconds
[2024-12-24T22:28:23.577+0000] {processor.py:186} INFO - Started process (PID=649) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:28:23.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:28:23.580+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:28:23.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:28:23.601+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:28:23.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:28:23.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:28:23.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.055 seconds
[2024-12-24T22:28:54.092+0000] {processor.py:186} INFO - Started process (PID=666) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:28:54.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:28:54.096+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:28:54.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:28:54.120+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:28:54.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:28:54.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:28:54.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.066 seconds
[2024-12-24T22:29:24.592+0000] {processor.py:186} INFO - Started process (PID=682) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:29:24.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:29:24.596+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:29:24.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:29:24.620+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:29:24.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:29:24.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:29:24.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.057 seconds
[2024-12-24T22:29:55.042+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:29:55.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:29:55.045+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:29:55.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:29:55.060+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:29:55.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:29:55.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:29:55.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.046 seconds
[2024-12-24T22:30:25.548+0000] {processor.py:186} INFO - Started process (PID=715) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:30:25.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:30:25.551+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:30:25.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:30:25.566+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:30:25.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:30:25.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:30:25.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.051 seconds
[2024-12-24T22:30:56.044+0000] {processor.py:186} INFO - Started process (PID=731) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:30:56.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:30:56.047+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:30:56.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:30:56.063+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:30:56.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:30:56.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:30:56.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.049 seconds
[2024-12-24T22:31:26.529+0000] {processor.py:186} INFO - Started process (PID=747) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:31:26.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:31:26.535+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:31:26.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:31:26.546+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:31:26.543+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:31:26.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:31:26.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.047 seconds
[2024-12-24T22:31:57.014+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:31:57.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:31:57.017+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:31:57.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:31:57.041+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:31:57.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:31:57.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:31:57.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.056 seconds
[2024-12-24T22:32:27.467+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:32:27.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:32:27.470+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:32:27.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:32:27.484+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:32:27.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:32:27.485+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:32:27.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.043 seconds
[2024-12-24T22:32:57.929+0000] {processor.py:186} INFO - Started process (PID=795) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:32:57.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:32:57.933+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:32:57.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:32:57.951+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:32:57.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:32:57.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:32:57.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.050 seconds
[2024-12-24T22:33:28.421+0000] {processor.py:186} INFO - Started process (PID=811) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:33:28.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:33:28.425+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:33:28.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:33:28.447+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:33:28.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:33:28.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:33:28.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.057 seconds
[2024-12-24T22:33:58.841+0000] {processor.py:186} INFO - Started process (PID=827) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:33:58.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:33:58.845+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:33:58.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:33:58.863+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:33:58.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:33:58.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:33:58.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.051 seconds
[2024-12-24T22:34:29.323+0000] {processor.py:186} INFO - Started process (PID=843) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:34:29.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:34:29.326+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:34:29.326+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:34:29.345+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:34:29.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:34:29.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:34:29.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.051 seconds
[2024-12-24T22:34:59.827+0000] {processor.py:186} INFO - Started process (PID=859) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:34:59.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:34:59.831+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:34:59.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:34:59.851+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:34:59.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:34:59.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:34:59.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.053 seconds
[2024-12-24T22:35:30.365+0000] {processor.py:186} INFO - Started process (PID=875) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:35:30.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:35:30.370+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:35:30.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:35:30.390+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:35:30.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:35:30.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:35:30.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.056 seconds
[2024-12-24T22:36:00.814+0000] {processor.py:186} INFO - Started process (PID=891) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:36:00.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:36:00.817+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:36:00.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:36:00.836+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:36:00.834+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:36:00.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:36:00.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.051 seconds
[2024-12-24T22:36:31.281+0000] {processor.py:186} INFO - Started process (PID=908) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:36:31.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:36:31.285+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:36:31.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:36:31.309+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:36:31.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:36:31.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:36:31.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.061 seconds
[2024-12-24T22:37:01.771+0000] {processor.py:186} INFO - Started process (PID=924) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:37:01.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:37:01.774+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:37:01.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:37:01.788+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:37:01.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:37:01.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:37:01.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.048 seconds
[2024-12-24T22:37:32.242+0000] {processor.py:186} INFO - Started process (PID=940) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:37:32.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:37:32.245+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:37:32.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:37:32.266+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:37:32.263+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:37:32.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:37:32.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.053 seconds
[2024-12-24T22:38:02.683+0000] {processor.py:186} INFO - Started process (PID=956) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:38:02.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:38:02.687+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:38:02.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:38:02.705+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:38:02.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:38:02.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:38:02.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.049 seconds
[2024-12-24T22:38:33.168+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:38:33.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:38:33.171+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:38:33.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:38:33.192+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:38:33.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:38:33.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:38:33.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.053 seconds
[2024-12-24T22:39:03.656+0000] {processor.py:186} INFO - Started process (PID=989) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:39:03.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:39:03.659+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:39:03.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:39:03.678+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:39:03.676+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:39:03.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:39:03.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.059 seconds
[2024-12-24T22:39:34.140+0000] {processor.py:186} INFO - Started process (PID=1005) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:39:34.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:39:34.144+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:39:34.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:39:34.167+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:39:34.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:39:34.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:39:34.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.059 seconds
[2024-12-24T22:40:04.630+0000] {processor.py:186} INFO - Started process (PID=1021) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:40:04.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:40:04.633+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:40:04.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:40:04.656+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:40:04.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:40:04.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:40:04.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.063 seconds
[2024-12-24T22:40:35.131+0000] {processor.py:186} INFO - Started process (PID=1037) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:40:35.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:40:35.134+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:40:35.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:40:35.151+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:40:35.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:40:35.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:40:35.174+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.048 seconds
[2024-12-24T22:41:05.570+0000] {processor.py:186} INFO - Started process (PID=1053) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:41:05.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:41:05.573+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:41:05.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:41:05.586+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:41:05.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:41:05.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:41:05.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.043 seconds
[2024-12-24T22:41:36.038+0000] {processor.py:186} INFO - Started process (PID=1069) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:41:36.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:41:36.042+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:41:36.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:41:36.063+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:41:36.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:41:36.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:41:36.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.055 seconds
[2024-12-24T22:42:06.529+0000] {processor.py:186} INFO - Started process (PID=1085) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:42:06.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:42:06.532+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:42:06.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:42:06.552+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:42:06.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:42:06.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:42:06.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.050 seconds
[2024-12-24T22:42:36.982+0000] {processor.py:186} INFO - Started process (PID=1101) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:42:36.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:42:36.985+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:42:36.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:42:37.006+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:42:37.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:42:37.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:42:37.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.051 seconds
[2024-12-24T22:43:07.489+0000] {processor.py:186} INFO - Started process (PID=1117) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:43:07.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:43:07.492+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:43:07.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:43:07.516+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:43:07.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:43:07.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:43:07.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.062 seconds
[2024-12-24T22:43:37.964+0000] {processor.py:186} INFO - Started process (PID=1133) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:43:37.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:43:37.969+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:43:37.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:43:37.989+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:43:37.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:43:37.990+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:43:38.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.060 seconds
[2024-12-24T22:44:08.415+0000] {processor.py:186} INFO - Started process (PID=1149) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:44:08.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:44:08.419+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:44:08.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:44:08.441+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:44:08.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:44:08.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:44:08.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.055 seconds
[2024-12-24T22:44:38.901+0000] {processor.py:186} INFO - Started process (PID=1165) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:44:38.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:44:38.907+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:44:38.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:44:38.922+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:44:38.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:44:38.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:44:38.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.060 seconds
[2024-12-24T22:45:09.350+0000] {processor.py:186} INFO - Started process (PID=1181) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:45:09.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:45:09.354+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:45:09.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:45:09.369+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:45:09.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:45:09.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:45:09.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.048 seconds
[2024-12-24T22:45:39.844+0000] {processor.py:186} INFO - Started process (PID=1197) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:45:39.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:45:39.847+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:45:39.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:45:39.863+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:45:39.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:45:39.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:45:39.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.049 seconds
[2024-12-24T22:46:10.303+0000] {processor.py:186} INFO - Started process (PID=1213) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:46:10.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:46:10.306+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:46:10.306+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:46:10.327+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:46:10.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:46:10.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:46:10.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.052 seconds
[2024-12-24T22:46:40.821+0000] {processor.py:186} INFO - Started process (PID=1229) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:46:40.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:46:40.826+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:46:40.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:46:40.849+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:46:40.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:46:40.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:46:40.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.070 seconds
[2024-12-24T22:47:11.298+0000] {processor.py:186} INFO - Started process (PID=1245) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:47:11.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:47:11.301+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:47:11.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:47:11.316+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:47:11.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:47:11.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:47:11.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.048 seconds
[2024-12-24T22:47:41.765+0000] {processor.py:186} INFO - Started process (PID=1261) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:47:41.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:47:41.768+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:47:41.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:47:41.782+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:47:41.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:47:41.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:47:41.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.050 seconds
[2024-12-24T22:48:12.248+0000] {processor.py:186} INFO - Started process (PID=1277) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:48:12.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:48:12.252+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:48:12.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:48:12.273+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:48:12.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:48:12.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:48:12.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.075 seconds
[2024-12-24T22:48:42.755+0000] {processor.py:186} INFO - Started process (PID=1293) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:48:42.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:48:42.758+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:48:42.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:48:42.774+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:48:42.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:48:42.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:48:42.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.047 seconds
[2024-12-24T22:49:13.228+0000] {processor.py:186} INFO - Started process (PID=1309) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:49:13.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:49:13.231+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:49:13.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:49:13.246+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:49:13.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:49:13.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:49:13.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.048 seconds
[2024-12-24T22:49:43.675+0000] {processor.py:186} INFO - Started process (PID=1325) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:49:43.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:49:43.678+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:49:43.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:49:43.699+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:49:43.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:49:43.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:49:43.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.056 seconds
[2024-12-24T22:50:14.123+0000] {processor.py:186} INFO - Started process (PID=1341) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:50:14.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:50:14.126+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:50:14.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:50:14.149+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:50:14.144+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:50:14.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:50:14.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.064 seconds
[2024-12-24T22:50:44.680+0000] {processor.py:186} INFO - Started process (PID=1357) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:50:44.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:50:44.690+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:50:44.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:50:44.704+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:50:44.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:50:44.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:50:44.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.056 seconds
[2024-12-24T22:51:15.162+0000] {processor.py:186} INFO - Started process (PID=1373) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:51:15.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:51:15.165+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:51:15.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:51:15.180+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:51:15.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:51:15.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:51:15.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.056 seconds
[2024-12-24T22:51:45.613+0000] {processor.py:186} INFO - Started process (PID=1389) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:51:45.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:51:45.616+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:51:45.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:51:45.629+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:51:45.626+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:51:45.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:51:45.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.042 seconds
[2024-12-24T22:52:16.077+0000] {processor.py:186} INFO - Started process (PID=1405) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:52:16.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:52:16.080+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:52:16.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:52:16.095+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:52:16.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:52:16.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:52:16.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.047 seconds
[2024-12-24T22:52:46.548+0000] {processor.py:186} INFO - Started process (PID=1421) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:52:46.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:52:46.551+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:52:46.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:52:46.572+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:52:46.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:52:46.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:52:46.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.055 seconds
[2024-12-24T22:53:17.045+0000] {processor.py:186} INFO - Started process (PID=1437) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:53:17.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:53:17.047+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:53:17.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:53:17.063+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:53:17.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:53:17.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:53:17.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.053 seconds
[2024-12-24T22:53:47.558+0000] {processor.py:186} INFO - Started process (PID=1453) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:53:47.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:53:47.561+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:53:47.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:53:47.580+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:53:47.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:53:47.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:53:47.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.075 seconds
[2024-12-24T22:54:18.062+0000] {processor.py:186} INFO - Started process (PID=1469) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:54:18.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:54:18.066+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:54:18.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:54:18.081+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:54:18.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:54:18.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:54:18.105+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.048 seconds
[2024-12-24T22:54:48.546+0000] {processor.py:186} INFO - Started process (PID=1485) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:54:48.546+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:54:48.548+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:54:48.548+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:54:48.561+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:54:48.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:54:48.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:54:48.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.047 seconds
[2024-12-24T22:55:19.065+0000] {processor.py:186} INFO - Started process (PID=1501) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:55:19.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:55:19.070+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:55:19.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:55:19.089+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:55:19.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:55:19.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:55:19.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.057 seconds
[2024-12-24T22:55:49.399+0000] {processor.py:186} INFO - Started process (PID=1517) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:55:49.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:55:49.403+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:55:49.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:55:49.433+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:55:49.427+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:55:49.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:55:49.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.070 seconds
[2024-12-24T22:56:19.903+0000] {processor.py:186} INFO - Started process (PID=1533) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:56:19.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:56:19.906+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:56:19.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:56:19.926+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:56:19.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:56:19.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:56:19.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.052 seconds
[2024-12-24T22:56:50.393+0000] {processor.py:186} INFO - Started process (PID=1549) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:56:50.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:56:50.397+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:56:50.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:56:50.418+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:56:50.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:56:50.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:56:50.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.070 seconds
[2024-12-24T22:57:20.850+0000] {processor.py:186} INFO - Started process (PID=1565) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:57:20.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:57:20.855+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:57:20.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:57:20.896+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:57:20.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:57:20.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:57:20.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.087 seconds
[2024-12-24T22:57:51.359+0000] {processor.py:186} INFO - Started process (PID=1587) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:57:51.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:57:51.362+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:57:51.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:57:51.387+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:57:51.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:57:51.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:57:51.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.062 seconds
[2024-12-24T22:58:21.855+0000] {processor.py:186} INFO - Started process (PID=1603) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:58:21.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:58:21.860+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:58:21.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:58:21.893+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:58:21.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:58:21.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:58:21.924+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.073 seconds
[2024-12-24T22:58:52.363+0000] {processor.py:186} INFO - Started process (PID=1619) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:58:52.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:58:52.366+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:58:52.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:58:52.390+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:58:52.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:58:52.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:58:52.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.056 seconds
[2024-12-24T22:59:22.834+0000] {processor.py:186} INFO - Started process (PID=1636) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:59:22.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:59:22.837+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:59:22.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:59:22.874+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:59:22.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:59:22.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:59:22.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.076 seconds
[2024-12-24T22:59:53.350+0000] {processor.py:186} INFO - Started process (PID=1652) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:59:53.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T22:59:53.354+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:59:53.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:59:53.391+0000] {logging_mixin.py:190} INFO - [2024-12-24T22:59:53.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T22:59:53.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T22:59:53.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.080 seconds
[2024-12-24T23:00:23.933+0000] {processor.py:186} INFO - Started process (PID=1668) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:00:23.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:00:23.936+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:00:23.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:00:23.974+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:00:23.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:00:23.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:00:24.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.078 seconds
[2024-12-24T23:00:54.451+0000] {processor.py:186} INFO - Started process (PID=1684) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:00:54.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:00:54.456+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:00:54.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:00:54.493+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:00:54.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:00:54.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:00:54.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.076 seconds
[2024-12-24T23:01:24.978+0000] {processor.py:186} INFO - Started process (PID=1699) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:01:24.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:01:24.982+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:01:24.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:01:25.022+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:01:25.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:01:25.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:01:25.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.084 seconds
[2024-12-24T23:01:55.495+0000] {processor.py:186} INFO - Started process (PID=1715) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:01:55.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:01:55.498+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:01:55.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:01:55.518+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:01:55.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:01:55.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:01:55.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.054 seconds
[2024-12-24T23:02:25.989+0000] {processor.py:186} INFO - Started process (PID=1731) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:02:25.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:02:25.992+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:02:25.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:02:26.019+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:02:26.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:02:26.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:02:26.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.062 seconds
[2024-12-24T23:02:56.465+0000] {processor.py:186} INFO - Started process (PID=1747) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:02:56.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:02:56.469+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:02:56.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:02:56.497+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:02:56.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:02:56.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:02:56.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.063 seconds
[2024-12-24T23:03:26.910+0000] {processor.py:186} INFO - Started process (PID=1763) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:03:26.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:03:26.915+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:03:26.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:03:26.940+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:03:26.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:03:26.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:03:26.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.062 seconds
[2024-12-24T23:03:57.376+0000] {processor.py:186} INFO - Started process (PID=1779) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:03:57.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:03:57.380+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:03:57.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:03:57.418+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:03:57.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:03:57.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:03:57.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.080 seconds
[2024-12-24T23:04:27.885+0000] {processor.py:186} INFO - Started process (PID=1795) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:04:27.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:04:27.891+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:04:27.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:04:27.933+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:04:27.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:04:27.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:04:27.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.089 seconds
[2024-12-24T23:04:58.406+0000] {processor.py:186} INFO - Started process (PID=1811) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:04:58.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:04:58.410+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:04:58.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:04:58.444+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:04:58.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:04:58.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:04:58.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.071 seconds
[2024-12-24T23:05:28.908+0000] {processor.py:186} INFO - Started process (PID=1827) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:05:28.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:05:28.912+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:05:28.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:05:28.943+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:05:28.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:05:28.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:05:28.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.067 seconds
[2024-12-24T23:05:59.383+0000] {processor.py:186} INFO - Started process (PID=1843) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:05:59.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:05:59.387+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:05:59.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:05:59.414+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:05:59.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:05:59.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:05:59.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.060 seconds
[2024-12-24T23:06:29.872+0000] {processor.py:186} INFO - Started process (PID=1859) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:06:29.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:06:29.876+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:06:29.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:06:29.911+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:06:29.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:06:29.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:06:29.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.076 seconds
[2024-12-24T23:07:00.364+0000] {processor.py:186} INFO - Started process (PID=1875) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:07:00.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:07:00.367+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:07:00.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:07:00.385+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:07:00.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:07:00.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:07:00.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.050 seconds
[2024-12-24T23:07:30.862+0000] {processor.py:186} INFO - Started process (PID=1892) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:07:30.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:07:30.866+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:07:30.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:07:30.894+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:07:30.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:07:30.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:07:30.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.064 seconds
[2024-12-24T23:08:01.377+0000] {processor.py:186} INFO - Started process (PID=1908) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:08:01.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:08:01.381+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:08:01.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:08:01.419+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:08:01.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:08:01.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:08:01.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.079 seconds
[2024-12-24T23:08:31.898+0000] {processor.py:186} INFO - Started process (PID=1924) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:08:31.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:08:31.902+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:08:31.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:08:31.941+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:08:31.932+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:08:31.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:08:31.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.082 seconds
[2024-12-24T23:09:02.386+0000] {processor.py:186} INFO - Started process (PID=1940) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:09:02.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:09:02.390+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:09:02.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:09:02.416+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:09:02.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:09:02.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:09:02.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.063 seconds
[2024-12-24T23:09:32.887+0000] {processor.py:186} INFO - Started process (PID=1956) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:09:32.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:09:32.890+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:09:32.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:09:32.914+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:09:32.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:09:32.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:09:32.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.062 seconds
[2024-12-24T23:10:03.391+0000] {processor.py:186} INFO - Started process (PID=1972) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:10:03.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:10:03.395+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:10:03.394+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:10:03.431+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:10:03.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:10:03.433+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:10:03.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.074 seconds
[2024-12-24T23:10:33.973+0000] {processor.py:186} INFO - Started process (PID=1988) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:10:33.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:10:33.976+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:10:33.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:10:33.996+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:10:33.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:10:33.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:10:34.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.049 seconds
[2024-12-24T23:11:04.482+0000] {processor.py:186} INFO - Started process (PID=2004) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:11:04.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:11:04.486+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:11:04.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:11:04.514+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:11:04.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:11:04.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:11:04.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.065 seconds
[2024-12-24T23:11:34.964+0000] {processor.py:186} INFO - Started process (PID=2020) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:11:34.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:11:34.968+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:11:34.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:11:35.000+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:11:34.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:11:35.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:11:35.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.072 seconds
[2024-12-24T23:12:05.473+0000] {processor.py:186} INFO - Started process (PID=2036) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:12:05.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:12:05.477+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:12:05.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:12:05.504+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:12:05.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:12:05.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:12:05.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.077 seconds
[2024-12-24T23:12:35.975+0000] {processor.py:186} INFO - Started process (PID=2052) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:12:35.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:12:35.978+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:12:35.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:12:36.002+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:12:35.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:12:36.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:12:36.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.060 seconds
[2024-12-24T23:13:06.481+0000] {processor.py:186} INFO - Started process (PID=2068) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:13:06.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:13:06.485+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:13:06.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:13:06.518+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:13:06.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:13:06.520+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:13:06.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.080 seconds
[2024-12-24T23:13:36.990+0000] {processor.py:186} INFO - Started process (PID=2084) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:13:36.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:13:36.995+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:13:36.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:13:37.033+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:13:37.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:13:37.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:13:37.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.078 seconds
[2024-12-24T23:14:07.489+0000] {processor.py:186} INFO - Started process (PID=2099) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:14:07.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:14:07.492+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:14:07.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:14:07.516+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:14:07.512+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:14:07.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:14:07.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.058 seconds
[2024-12-24T23:14:37.961+0000] {processor.py:186} INFO - Started process (PID=2115) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:14:37.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:14:37.966+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:14:37.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:14:38.007+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:14:37.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:14:38.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:14:38.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.086 seconds
[2024-12-24T23:15:08.426+0000] {processor.py:186} INFO - Started process (PID=2131) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:15:08.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:15:08.429+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:15:08.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:15:08.456+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:15:08.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:15:08.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:15:08.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.063 seconds
[2024-12-24T23:15:38.923+0000] {processor.py:186} INFO - Started process (PID=2147) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:15:38.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:15:38.926+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:15:38.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:15:38.956+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:15:38.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:15:38.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:15:38.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.073 seconds
[2024-12-24T23:16:09.443+0000] {processor.py:186} INFO - Started process (PID=2163) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:16:09.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:16:09.449+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:16:09.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:16:09.493+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:16:09.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:16:09.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:16:09.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.092 seconds
[2024-12-24T23:16:39.668+0000] {processor.py:186} INFO - Started process (PID=2179) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:16:39.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:16:39.704+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:16:39.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:16:39.748+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:16:39.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:16:39.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:16:39.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.109 seconds
[2024-12-24T23:17:10.179+0000] {processor.py:186} INFO - Started process (PID=2195) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:17:10.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:17:10.184+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:17:10.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:17:10.217+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:17:10.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:17:10.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:17:10.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.073 seconds
[2024-12-24T23:17:40.672+0000] {processor.py:186} INFO - Started process (PID=2211) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:17:40.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:17:40.676+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:17:40.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:17:40.709+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:17:40.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:17:40.711+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:17:40.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.073 seconds
[2024-12-24T23:18:11.220+0000] {processor.py:186} INFO - Started process (PID=2228) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:18:11.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:18:11.225+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:18:11.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:18:11.242+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:18:11.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:18:11.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:18:11.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.069 seconds
[2024-12-24T23:18:41.747+0000] {processor.py:186} INFO - Started process (PID=2244) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:18:41.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:18:41.753+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:18:41.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:18:41.790+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:18:41.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:18:41.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:18:41.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.082 seconds
[2024-12-24T23:19:12.269+0000] {processor.py:186} INFO - Started process (PID=2260) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:19:12.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:19:12.272+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:19:12.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:19:12.303+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:19:12.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:19:12.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:19:12.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.068 seconds
[2024-12-24T23:19:42.735+0000] {processor.py:186} INFO - Started process (PID=2276) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:19:42.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:19:42.738+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:19:42.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:19:42.764+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:19:42.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:19:42.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:19:42.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.064 seconds
[2024-12-24T23:20:13.227+0000] {processor.py:186} INFO - Started process (PID=2292) to work on /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:20:13.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/api_to_kafka_dag.py for tasks to queue
[2024-12-24T23:20:13.230+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:20:13.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:20:13.256+0000] {logging_mixin.py:190} INFO - [2024-12-24T23:20:13.253+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/api_to_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_to_kafka_dag.py", line 6, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[2024-12-24T23:20:13.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/api_to_kafka_dag.py
[2024-12-24T23:20:13.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/api_to_kafka_dag.py took 0.060 seconds
